#!/usr/bin/env node
/* Works out the shop's selling prices from the supplier prices in worker/suppliers.js and writes
   them into index.html (the block between the "prices:begin" and "prices:end" markers).

   Rule: cheapest supplier price, VAT added when the supplier quotes ex VAT (the company is not VAT
   registered, so the full price is the real cost), then the mark-up. A product with no priced
   supplier stays "Trade price on request" in the shop.

   Run after changing prices or the mark-up:   node worker/build-prices.js
   (build.py runs it automatically.) */
const fs = require('fs');
const path = require('path');

const MARKUP = 20;      // per cent on top of the price paid
const VAT = 0.2;
const root = path.resolve(__dirname, '..');
const page = path.join(root, 'index.html');

import(path.join(__dirname, 'suppliers.js')).then(m => {
  const S = m.default;
  const sell = {}, from = {};
  let latest = '';
  for (const [id, list] of Object.entries(S)) {
    if (!Array.isArray(list)) continue;
    let best = null;
    for (const x of list) {
      if (x.alt) continue;   // a different product offered as an alternative: never sets the shop price
      const p = /£\s*([0-9]+(?:\.[0-9]+)?)/.exec(x.price || ''); if (!p) continue;
      const n = parseFloat(p[1]);
      const inc = /inc\.? ?VAT/i.test(x.price) ? n : n * (1 + VAT);
      if (!best || inc < best.inc) best = { inc, price: x.price, checked: x.checked || '' };
    }
    if (!best) continue;
    sell[id] = Math.round(best.inc * (1 + MARKUP / 100) * 100) / 100;
    if (/–|-\s*£|\(/.test(best.price.replace(/\((was|ex\.? ?VAT)[^)]*\)/gi, ''))) from[id] = true;   // a range or a size-specific price: show "from"
    if (best.checked > latest) latest = best.checked;
  }
  // Kits (products with a "kit" list in index.html) cost the sum of their parts' shop prices, so a kit is never
  // dearer or cheaper than buying the same things one by one. A kit with an unpriced part stays "on request".
  let html0 = fs.readFileSync(page, 'utf8');
  const sm = html0.match(/<script>([\s\S]*?)<\/script>/);
  const SITE = sm ? new Function(sm[1] + '\nreturn SITE;')() : { products: [] };
  let kits = 0;
  for (const p of SITE.products || []) {
    if (!Array.isArray(p.kit) || !p.kit.length) continue;
    if (!p.kit.every(([id]) => sell[id] > 0)) { console.warn(`kit ${p.id}: a part has no price, left on request`); continue; }
    sell[p.id] = Math.round(p.kit.reduce((t, [id, q]) => t + sell[id] * (q || 1), 0) * 100) / 100;
    if (p.kit.some(([id]) => from[id])) from[p.id] = true;
    kits++;
  }
  const block = `  /* prices:begin (generated by worker/build-prices.js from worker/suppliers.js: do not edit by hand) */
  pricing: { markup: ${MARKUP}, updated: ${JSON.stringify(latest)}, sell: ${JSON.stringify(sell)}, from: ${JSON.stringify(from)} },
  /* prices:end */`;
  let html = fs.readFileSync(page, 'utf8');
  const re = /  \/\* prices:begin[\s\S]*?prices:end \*\//;
  if (!re.test(html)) { console.error('markers not found in index.html'); process.exit(1); }
  html = html.replace(re, block);
  fs.writeFileSync(page, html);
  console.log(`prices: ${Object.keys(sell).length} products priced at +${MARKUP}% (${kits} kits from their parts)`);
});
