/* Generated by worker/build-catalogue.js from index.html. Do not edit by hand. */
export const RANGES = [
  {
    "id": "materials",
    "name": "Materials",
    "groups": "brand"
  },
  {
    "id": "tools",
    "name": "Tools",
    "groups": "group"
  },
  {
    "id": "workwear",
    "name": "Workwear and PPE",
    "groups": "group"
  }
];
export const PRODUCTS = [
  {
    "id": "fb750-intubatt",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FB750 Intubatt",
    "size": "1200 × 600 × 50 mm",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fb750-intubatt/"
  },
  {
    "id": "fs702-intumastic",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FS702 Intumastic",
    "size": "310 ml and 600 ml, white or grey",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fs702-intumastic-fire-resistant-acrylic-sealant/"
  },
  {
    "id": "fs709-sealant",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FS709 HP Intumescent Sealant",
    "size": "310 ml, anthracite",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fs709-hp-intumescent-sealant/"
  },
  {
    "id": "fp302-intustrap",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FP302 Intustrap",
    "size": "60 mm × 4 mm × 25 m roll",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fp302-intustrap-intumescent-strap/"
  },
  {
    "id": "fp170-intucollar",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FP170 Intucollar",
    "size": "Sized to the pipe",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fp170-intucollar-intumescent-pipe-collar/"
  },
  {
    "id": "fr230-intucompound",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FR230 Intucompound",
    "size": "20 kg bag",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fr230-intucompound-fire-mortar/"
  },
  {
    "id": "fi025-intuflex",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FI025 Intuflex",
    "size": "Supplied in rolls",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fi025-intuflex-insulation-wrap/"
  },
  {
    "id": "sc902-steel-coating",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "SC902 steel coating",
    "size": "25 kg two-pack",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/sc902-intumescent-steel-coating-fast-track-on-site-and-offsite/"
  },
  {
    "id": "sc802-steel-coating",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "SC802 steel coating",
    "size": "5 L and 25 kg",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/sc802-intumescent-steel-coating-on-site-water-based/"
  },
  {
    "id": "stopseal-batt",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Stopseal Batt",
    "size": "1200 × 600 × 50 mm",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/coatingcoated-batts/stopsealbatt/"
  },
  {
    "id": "pyrocoustic-sealant",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Pyrocoustic Sealant",
    "size": "310 ml and 600 ml, white",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/sealant/pyrocousticsealant/"
  },
  {
    "id": "pyropro-hpe-sealant",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PyroPro HPE Sealant",
    "size": "310 ml and 600 ml, anthracite",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/sealant/pyroprohpesealant/"
  },
  {
    "id": "silverseal-compound",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Silverseal Compound",
    "size": "20 kg bag",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/mortar/silversealcompound/"
  },
  {
    "id": "pipebloc-pcp-collar",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PipeBloc PCP Collar",
    "size": "Sized to the pipe",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/collarwrap/pipeblocpcpcollar/"
  },
  {
    "id": "pipebloc-pwp-wrap",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PipeBloc PWP Wrap",
    "size": "40 mm wide, sized to the pipe",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/collarwrap/pipeblocpwpwrap/"
  },
  {
    "id": "tool-gun-310",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Cox",
    "name": "PowerFlow Combi 310 ml gun",
    "size": "Takes: 310 ml cartridges",
    "link": ""
  },
  {
    "id": "tool-gun-600",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Cox",
    "name": "Ultraflow 600 ml sausage gun",
    "size": "Takes: 600 ml sausages and 310 ml cartridges",
    "link": ""
  },
  {
    "id": "tool-gun-battery",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Milwaukee",
    "name": "M12 cordless sealant gun",
    "size": "Takes: 310 ml or 400 ml (barrel version 600 ml)",
    "link": ""
  },
  {
    "id": "tool-finishing",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Cramer",
    "name": "Fugi sealant finishing kit",
    "size": "Set: Five profiles",
    "link": ""
  },
  {
    "id": "tool-batt-saw",
    "category": "tools",
    "group": "Cutting",
    "brand": "Bahco",
    "name": "Insulation saw, 22 inch",
    "size": "Blade: 560 mm, 7 TPI",
    "link": ""
  },
  {
    "id": "tool-knife",
    "category": "tools",
    "group": "Cutting",
    "brand": "Stanley",
    "name": "FatMax retractable knife with blades",
    "size": "Blades: Pack of 50 heavy-duty",
    "link": ""
  },
  {
    "id": "tool-hole-saw",
    "category": "tools",
    "group": "Cutting",
    "brand": "Various",
    "name": "Hole saw set for batt and board",
    "size": "Sizes: 32 to 152 mm",
    "link": ""
  },
  {
    "id": "tool-paddle",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Various",
    "name": "Compound mixing paddle, M14",
    "size": "Fitting: M14, for a paddle mixer or SDS drill with adaptor",
    "link": ""
  },
  {
    "id": "tool-tub",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Gorilla Tub",
    "name": "Flexible mixing tub, 26 L",
    "size": "Capacity: 26 litres",
    "link": ""
  },
  {
    "id": "tool-trowel",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Marshalltown",
    "name": "Margin trowel, 150 mm",
    "size": "Blade: 150 × 50 mm",
    "link": ""
  },
  {
    "id": "tool-backer-rod",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Various",
    "name": "Closed-cell backer rod",
    "size": "Sizes: 10, 15, 20 and 25 mm",
    "link": ""
  },
  {
    "id": "tool-wet-film",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Elcometer",
    "name": "Wet film comb, 25 to 2000 µm",
    "size": "Range: 25 to 2000 microns",
    "link": ""
  },
  {
    "id": "tool-dft-gauge",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Elcometer",
    "name": "Dry film thickness gauge",
    "size": "Reads: Ferrous and non-ferrous, 0 to 1500 µm",
    "link": ""
  },
  {
    "id": "tool-labels",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Various",
    "name": "Firestop identification labels",
    "size": "Pack: Roll of 100",
    "link": ""
  },
  {
    "id": "tool-torch",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Various",
    "name": "Rechargeable LED head torch",
    "size": "Output: Around 600 lumens",
    "link": ""
  },
  {
    "id": "tool-tape",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Stanley",
    "name": "Tape measure, 8 m",
    "size": "Length: 8 m, 32 mm blade",
    "link": ""
  },
  {
    "id": "ppe-ffp3",
    "category": "workwear",
    "group": "Respiratory",
    "brand": "3M",
    "name": "Aura FFP3 respirators, box of 10",
    "size": "Standard: EN 149 FFP3",
    "link": ""
  },
  {
    "id": "ppe-half-mask",
    "category": "workwear",
    "group": "Respiratory",
    "brand": "3M",
    "name": "Half-mask respirator with P3 filters",
    "size": "Filters: P3 R particulate; A2P3 for solvent-based coatings",
    "link": ""
  },
  {
    "id": "ppe-nitrile",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Various",
    "name": "Nitrile gloves, box of 100",
    "size": "Pack: Box of 100",
    "link": ""
  },
  {
    "id": "ppe-cut-gloves",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Various",
    "name": "Cut-resistant work gloves",
    "size": "Standard: EN 388, cut level D",
    "link": ""
  },
  {
    "id": "ppe-glasses",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Bollé",
    "name": "Safety glasses, clear anti-fog",
    "size": "Standard: EN 166",
    "link": ""
  },
  {
    "id": "ppe-earplugs",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Various",
    "name": "Disposable earplugs, box of 200 pairs",
    "size": "Attenuation: SNR 37 dB",
    "link": ""
  },
  {
    "id": "ppe-hard-hat",
    "category": "workwear",
    "group": "Clothing",
    "brand": "JSP",
    "name": "Vented safety helmet",
    "size": "Standard: EN 397",
    "link": ""
  },
  {
    "id": "ppe-hi-vis",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Various",
    "name": "Hi-vis vest, class 2",
    "size": "Standard: EN ISO 20471 class 2",
    "link": ""
  },
  {
    "id": "ppe-trousers",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Snickers",
    "name": "Stretch work trousers with knee pad pockets",
    "size": "Sizes: Waist 30 to 44, three leg lengths",
    "link": ""
  },
  {
    "id": "ppe-knee-pads",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Snickers",
    "name": "Knee pads for pocket trousers",
    "size": "Standard: EN 14404 type 2",
    "link": ""
  },
  {
    "id": "ppe-boots",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Various",
    "name": "S3 safety boots",
    "size": "Standard: EN ISO 20345 S3",
    "link": ""
  },
  {
    "id": "ppe-coverall",
    "category": "workwear",
    "group": "Clothing",
    "brand": "DuPont",
    "name": "Tyvek disposable coveralls",
    "size": "Standard: Type 5 and 6",
    "link": ""
  }
];
