/* Generated by worker/build-catalogue.js from index.html. Do not edit by hand. */
export const RANGES = [
  {
    "id": "materials",
    "name": "Materials",
    "groups": "brand"
  },
  {
    "id": "tools",
    "name": "Tools",
    "groups": "group"
  },
  {
    "id": "workwear",
    "name": "Workwear and PPE",
    "groups": "group"
  }
];
export const PRODUCTS = [
  {
    "id": "fb750-intubatt",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FB750 Intubatt",
    "image": "images/products/fb750-intubatt.jpg",
    "size": "1200 × 600 × 50 mm",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fb750-intubatt/"
  },
  {
    "id": "fs702-intumastic",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FS702 Intumastic",
    "image": "images/products/fs702-intumastic.jpg",
    "size": "310 ml and 600 ml, white or grey",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fs702-intumastic-fire-resistant-acrylic-sealant/"
  },
  {
    "id": "fs709-sealant",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FS709 HP Intumescent Sealant",
    "image": "images/products/fs709-sealant.jpg",
    "size": "310 ml, anthracite",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fs709-hp-intumescent-sealant/"
  },
  {
    "id": "fp302-intustrap",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FP302 Intustrap",
    "image": "images/products/fp302-intustrap.jpg",
    "size": "60 mm × 4 mm × 25 m roll",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fp302-intustrap-intumescent-strap/"
  },
  {
    "id": "fp170-intucollar",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FP170 Intucollar",
    "image": "images/products/fp170-intucollar.jpg",
    "size": "Sized to the pipe",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fp170-intucollar-intumescent-pipe-collar/"
  },
  {
    "id": "fr230-intucompound",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FR230 Intucompound",
    "image": "images/products/fr230-intucompound.jpg",
    "size": "20 kg bag",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fr230-intucompound-fire-mortar/"
  },
  {
    "id": "fi025-intuflex",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "FI025 Intuflex",
    "image": "images/products/fi025-intuflex.jpg",
    "size": "Supplied in rolls",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/fi025-intuflex-insulation-wrap/"
  },
  {
    "id": "sc902-steel-coating",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "SC902 steel coating",
    "image": "images/products/sc902-steel-coating.jpg",
    "size": "25 kg two-pack",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/sc902-intumescent-steel-coating-fast-track-on-site-and-offsite/"
  },
  {
    "id": "sc802-steel-coating",
    "category": "materials",
    "group": "Nullifire",
    "brand": "Nullifire",
    "name": "SC802 steel coating",
    "image": "images/products/sc802-steel-coating.jpg",
    "size": "5 L and 25 kg",
    "link": "https://www.nullifire.com/en-gb/products-systems/product-finder/sc802-intumescent-steel-coating-on-site-water-based/"
  },
  {
    "id": "stopseal-batt",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Stopseal Batt",
    "image": "images/products/stopseal-batt.jpg",
    "size": "1200 × 600 × 50 mm",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/coatingcoated-batts/stopsealbatt/"
  },
  {
    "id": "pyrocoustic-sealant",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Pyrocoustic Sealant",
    "image": "images/products/pyrocoustic-sealant.jpg",
    "size": "310 ml and 600 ml, white",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/sealant/pyrocousticsealant/"
  },
  {
    "id": "pyropro-hpe-sealant",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PyroPro HPE Sealant",
    "image": "images/products/pyropro-hpe-sealant.jpg",
    "size": "310 ml and 600 ml, anthracite",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/sealant/pyroprohpesealant/"
  },
  {
    "id": "silverseal-compound",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "Silverseal Compound",
    "image": "images/products/silverseal-compound.jpg",
    "size": "20 kg bag",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/mortar/silversealcompound/"
  },
  {
    "id": "pipebloc-pcp-collar",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PipeBloc PCP Collar",
    "image": "images/products/pipebloc-pcp-collar.jpg",
    "size": "Sized to the pipe",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/collarwrap/pipeblocpcpcollar/"
  },
  {
    "id": "pipebloc-pwp-wrap",
    "category": "materials",
    "group": "FSi Promat",
    "brand": "FSi Promat",
    "name": "PipeBloc PWP Wrap",
    "image": "images/products/pipebloc-pwp-wrap.jpg",
    "size": "40 mm wide, sized to the pipe",
    "link": "https://www.promat.com/en-gb/construction/products-systems/products/fire-stopping/collarwrap/pipeblocpwpwrap/"
  },
  {
    "id": "tool-gun-310",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "No Nonsense",
    "name": "Premium sealant gun",
    "image": "images/products/tool-gun-premium.jpg",
    "size": "Takes: Standard 310 ml cartridges",
    "link": ""
  },
  {
    "id": "tool-gun-600",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "No Nonsense",
    "name": "600 ml foil and cartridge gun",
    "image": "images/products/tool-gun-600.jpg",
    "size": "Takes: 600 ml sausages and 310 ml cartridges",
    "link": ""
  },
  {
    "id": "tool-gun-battery",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Milwaukee",
    "name": "M12 cordless sealant gun, 600 ml",
    "image": "images/products/tool-gun-battery.jpg",
    "size": "Takes: 310 ml or 400 ml (barrel version 600 ml)",
    "link": ""
  },
  {
    "id": "tool-finishing",
    "category": "tools",
    "group": "Sealant guns",
    "brand": "Cramer",
    "name": "Fugi sealant finishing kit, 3 profiles",
    "image": "images/products/tool-finishing.jpg",
    "size": "Set: Three profiles",
    "link": ""
  },
  {
    "id": "tool-batt-saw",
    "category": "tools",
    "group": "Cutting",
    "brand": "Bahco",
    "name": "Insulation saw, 550 mm",
    "image": "images/products/tool-batt-saw.jpg",
    "size": "Blade: 560 mm, 7 TPI",
    "link": ""
  },
  {
    "id": "tool-knife",
    "category": "tools",
    "group": "Cutting",
    "brand": "Stanley",
    "name": "FatMax retractable knife",
    "image": "images/products/tool-knife.jpg",
    "size": "Blades: Pack of 50 heavy-duty",
    "link": ""
  },
  {
    "id": "tool-hole-saw",
    "category": "tools",
    "group": "Cutting",
    "brand": "Erbauer",
    "name": "Multi-material hole saw set, 11 pieces",
    "image": "images/products/tool-hole-saw.jpg",
    "size": "Sizes: 11 saws, 19 to 76 mm, with arbors",
    "link": ""
  },
  {
    "id": "tool-paddle",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Erbauer",
    "name": "Mixing paddle, 120 mm, M14",
    "image": "images/products/tool-paddle.jpg",
    "size": "Fitting: M14, for a paddle mixer or SDS drill with adaptor",
    "link": ""
  },
  {
    "id": "tool-tub",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Red Gorilla",
    "name": "Flexible mixing tub, 26 L",
    "image": "images/products/tool-tub.jpg",
    "size": "Capacity: 26 litres",
    "link": ""
  },
  {
    "id": "tool-trowel",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Marshalltown",
    "name": "Margin trowel, 127 mm",
    "image": "images/products/tool-trowel.jpg",
    "size": "Blade: 127 × 50 mm",
    "link": ""
  },
  {
    "id": "tool-backer-rod",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Everbuild",
    "name": "Closed-cell backer rod, 10 mm × 10 m",
    "image": "images/products/tool-backer-rod.jpg",
    "size": "Size: 10 mm diameter, other sizes to order",
    "link": ""
  },
  {
    "id": "tool-wet-film",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Various",
    "name": "Stainless wet film comb",
    "image": "images/products/tool-wet-film.jpg",
    "size": "Range: 25 to 2000 microns",
    "link": ""
  },
  {
    "id": "tool-dft-gauge",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Elcometer",
    "name": "Dry film thickness gauge",
    "image": "images/products/tool-dft-gauge.svg",
    "size": "Reads: Ferrous and non-ferrous, 0 to 1500 µm",
    "link": ""
  },
  {
    "id": "tool-labels",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Limitless Innovations",
    "name": "Firestop identification labels, 100 × 60 mm",
    "image": "images/products/tool-labels.jpg",
    "size": "Pack: Roll of 100",
    "link": ""
  },
  {
    "id": "tool-torch",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Nebo",
    "name": "Rechargeable LED head torch",
    "image": "images/products/tool-torch.jpg",
    "size": "Output: Around 600 lumens",
    "link": ""
  },
  {
    "id": "tool-tape",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Stanley",
    "name": "FatMax tape measure, 8 m",
    "image": "images/products/tool-tape.jpg",
    "size": "Length: 8 m, 32 mm blade",
    "link": ""
  },
  {
    "id": "tool-combi-drill",
    "category": "tools",
    "group": "Power tools",
    "brand": "DeWalt",
    "name": "DCD796 18V XR brushless combi drill kit, 1 × 5.0 Ah",
    "image": "images/products/tool-combi-drill.jpg",
    "size": "Voltage: 18 V",
    "link": ""
  },
  {
    "id": "tool-sds-drill",
    "category": "tools",
    "group": "Power tools",
    "brand": "DeWalt",
    "name": "DCH172 18V XR compact SDS+ hammer drill, body only",
    "image": "images/products/tool-sds-drill.jpg",
    "size": "Voltage: 18 V",
    "link": ""
  },
  {
    "id": "tool-multi-tool",
    "category": "tools",
    "group": "Power tools",
    "brand": "DeWalt",
    "name": "DCS355 18V XR brushless multi-tool, body only",
    "image": "images/products/tool-multi-tool.jpg",
    "size": "Voltage: 18 V",
    "link": ""
  },
  {
    "id": "tool-mixer",
    "category": "tools",
    "group": "Mixing and application",
    "brand": "Makita",
    "name": "DUT130Z 18V LXT brushless mixer, body only",
    "image": "images/products/tool-mixer.jpg",
    "size": "Voltage: 18 V",
    "link": ""
  },
  {
    "id": "tool-laser-measure",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Bosch Professional",
    "name": "GLM 40-31 laser measure",
    "image": "images/products/tool-laser-measure.jpg",
    "size": "Protection: IP65",
    "link": ""
  },
  {
    "id": "tool-spirit-level",
    "category": "tools",
    "group": "Marking and inspection",
    "brand": "Stabila",
    "name": "Type 70 spirit level, 600 mm",
    "image": "images/products/tool-spirit-level.jpg",
    "size": "Length: 60 cm",
    "link": ""
  },
  {
    "id": "tool-screwdriver-set",
    "category": "tools",
    "group": "Kit and access",
    "brand": "Wera",
    "name": "Kraftform Plus 334/355/6 screwdriver set, PZ and slotted",
    "image": "images/products/tool-screwdriver-set.jpg",
    "size": "Pieces: 6 with rack",
    "link": ""
  },
  {
    "id": "tool-hacksaw",
    "category": "tools",
    "group": "Cutting",
    "brand": "Bahco",
    "name": "325 Ergo hacksaw, 300 mm",
    "image": "images/products/tool-hacksaw.jpg",
    "size": "Blade length: 300 mm",
    "link": ""
  },
  {
    "id": "tool-bag",
    "category": "tools",
    "group": "Kit and access",
    "brand": "DeWalt",
    "name": "TSTAK soft tool bag",
    "image": "images/products/tool-bag.jpg",
    "size": "Fabric: 1200 denier polyester",
    "link": ""
  },
  {
    "id": "tool-work-light",
    "category": "tools",
    "group": "Power tools",
    "brand": "DeWalt",
    "name": "DCL050 18V XR LED area light, body only",
    "image": "images/products/tool-work-light.jpg",
    "size": "Output: 250 to 500 lumens",
    "link": ""
  },
  {
    "id": "tool-work-platform",
    "category": "tools",
    "group": "Kit and access",
    "brand": "Youngman",
    "name": "Odd Job aluminium work platform",
    "image": "images/products/tool-work-platform.jpg",
    "size": "Material: Aluminium",
    "link": ""
  },
  {
    "id": "ppe-ffp3",
    "category": "workwear",
    "group": "Respiratory",
    "brand": "JSP",
    "name": "SpringFit FFP3 respirators, pack of 10",
    "image": "images/products/ppe-ffp3.jpg",
    "size": "Standard: EN 149 FFP3",
    "link": ""
  },
  {
    "id": "ppe-half-mask",
    "category": "workwear",
    "group": "Respiratory",
    "brand": "3M",
    "name": "Half-mask respirator kit with P3 filters",
    "image": "images/products/ppe-half-mask.jpg",
    "size": "Filters: P3 R particulate; A2P3 for solvent-based coatings",
    "link": ""
  },
  {
    "id": "ppe-nitrile",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Various",
    "name": "Nitrile gloves, box of 100",
    "image": "images/products/ppe-nitrile.jpg",
    "size": "Pack: Box of 100",
    "link": ""
  },
  {
    "id": "ppe-cut-gloves",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "MCR Safety",
    "name": "Cut-resistant work gloves",
    "image": "images/products/ppe-cut-gloves.jpg",
    "size": "Standard: EN 388, cut level D",
    "link": ""
  },
  {
    "id": "ppe-glasses",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Bollé",
    "name": "Contour safety glasses, clear",
    "image": "images/products/ppe-glasses.jpg",
    "size": "Standard: EN 166",
    "link": ""
  },
  {
    "id": "ppe-earplugs",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "Howard Leight",
    "name": "Foam earplugs, 200 pairs",
    "image": "images/products/ppe-earplugs.jpg",
    "size": "Attenuation: SNR 37 dB",
    "link": ""
  },
  {
    "id": "ppe-hard-hat",
    "category": "workwear",
    "group": "Clothing",
    "brand": "JSP",
    "name": "EVO3 vented safety helmet",
    "image": "images/products/ppe-hard-hat.jpg",
    "size": "Standard: EN 397",
    "link": ""
  },
  {
    "id": "ppe-hi-vis",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Site",
    "name": "Hi-vis vest, class 2",
    "image": "images/products/ppe-hi-vis.jpg",
    "size": "Standard: EN ISO 20471 class 2",
    "link": ""
  },
  {
    "id": "ppe-trousers",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Snickers",
    "name": "6241 stretch work trousers",
    "image": "images/products/ppe-trousers.jpg",
    "size": "Sizes: Waist 30 to 44, three leg lengths",
    "link": ""
  },
  {
    "id": "ppe-knee-pads",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Snickers",
    "name": "9110 knee pad inserts",
    "image": "images/products/ppe-knee-pads.jpg",
    "size": "Standard: EN 14404 type 2",
    "link": ""
  },
  {
    "id": "ppe-boots",
    "category": "workwear",
    "group": "Clothing",
    "brand": "CAT",
    "name": "Holton S3 safety boots",
    "image": "images/products/ppe-boots.jpg",
    "size": "Standard: EN ISO 20345 S3",
    "link": ""
  },
  {
    "id": "ppe-coverall",
    "category": "workwear",
    "group": "Clothing",
    "brand": "DuPont",
    "name": "Tyvek disposable coverall",
    "image": "images/products/ppe-coverall.jpg",
    "size": "Standard: Type 5 and 6",
    "link": ""
  },
  {
    "id": "ppe-cut-gloves-dewalt",
    "category": "workwear",
    "group": "Hands and eyes",
    "brand": "DeWalt",
    "name": "Cut D touchscreen work gloves",
    "image": "images/products/ppe-cut-gloves-dewalt.jpg",
    "size": "Cut level: D",
    "link": ""
  },
  {
    "id": "ppe-p3-filters",
    "category": "workwear",
    "group": "Respiratory",
    "brand": "3M",
    "name": "2135 P3 particulate filters, 1 pair",
    "image": "images/products/ppe-p3-filters.jpg",
    "size": "Protection: P3",
    "link": ""
  },
  {
    "id": "ppe-hi-vis-jacket",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Portwest",
    "name": "C465 hi-vis 3-in-1 bomber jacket",
    "image": "images/products/ppe-hi-vis-jacket.jpg",
    "size": "Seams: Waterproof, taped",
    "link": ""
  },
  {
    "id": "ppe-safety-boots",
    "category": "workwear",
    "group": "Clothing",
    "brand": "DeWalt",
    "name": "Titanium S3 safety boots, wheat",
    "image": "images/products/ppe-safety-boots.jpg",
    "size": "Safety rating: S3 WR SRA",
    "link": ""
  },
  {
    "id": "ppe-knee-pads-strap",
    "category": "workwear",
    "group": "Clothing",
    "brand": "Portwest",
    "name": "KP40 Ultimate gel knee pads, strap-on",
    "image": "images/products/ppe-knee-pads-strap.jpg",
    "size": "Standard: EN 14404 Type 1 Level 1",
    "link": ""
  }
];
export const LOCK_PHOTOS = [
  {
    "src": "images/arch/battersea-1920.webp",
    "srcset": "images/arch/battersea-1280.webp 1280w, images/arch/battersea-1920.webp 1920w, images/arch/battersea-2560.webp 2560w, images/arch/battersea-3840.webp 3840w",
    "focus": "50% 38%",
    "place": "Battersea Power Station",
    "alt": "Battersea Power Station and its four chimneys",
    "credit": {
      "by": "Matt Brown",
      "licence": "CC BY 2.0",
      "url": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Battersea_Power_Station_2023-11-29.jpg"
    }
  },
  {
    "src": "images/arch/vantage-1500.webp",
    "srcset": "images/arch/vantage-1280.webp 1280w, images/arch/vantage-1500.webp 1500w",
    "focus": "50% 72%",
    "place": "Vantage Data Centre, North Acton",
    "alt": "The reflective facade of the Vantage data centre behind trees",
    "credit": {
      "by": "Vantage Data Centers"
    }
  },
  {
    "src": "images/arch/bloomberg-1920.webp",
    "srcset": "images/arch/bloomberg-1280.webp 1280w, images/arch/bloomberg-1920.webp 1920w",
    "focus": "50% 45%",
    "place": "Bloomberg London, City of London",
    "alt": "The bronze-finned facade of Bloomberg London",
    "credit": {
      "by": "The wub",
      "licence": "CC BY-SA 4.0",
      "url": "https://creativecommons.org/licenses/by-sa/4.0/",
      "source": "https://commons.wikimedia.org/wiki/File:Bloomberg_London_exterior_-_Cannon_Street,_Walbrook.jpg"
    }
  },
  {
    "src": "images/arch/silvertown-1920.webp",
    "srcset": "images/arch/silvertown-1280.webp 1280w, images/arch/silvertown-1920.webp 1920w",
    "focus": "50% 55%",
    "place": "Silvertown Tunnel",
    "alt": "The Silvertown Tunnel entrance",
    "credit": {
      "by": "Tom Page",
      "licence": "CC BY-SA 2.0",
      "url": "https://creativecommons.org/licenses/by-sa/2.0/",
      "source": "https://commons.wikimedia.org/wiki/File:2024-12-17_Silvertown_Tunnel_entrance.jpg"
    }
  },
  {
    "src": "images/arch/city-hall-1920.webp",
    "srcset": "images/arch/city-hall-1280.webp 1280w, images/arch/city-hall-1920.webp 1920w",
    "focus": "50% 50%",
    "place": "City Hall, Royal Victoria Dock",
    "alt": "City Hall at Royal Victoria Dock",
    "credit": {
      "by": "Matt Brown",
      "licence": "CC BY 2.0",
      "url": "https://creativecommons.org/licenses/by/2.0/",
      "source": "https://commons.wikimedia.org/wiki/File:City_Hall_with_flags_January_19,_2022.jpg"
    }
  },
  {
    "src": "images/arch/one-canada-square-1920.webp",
    "srcset": "images/arch/one-canada-square-1280.webp 1280w, images/arch/one-canada-square-1920.webp 1920w",
    "focus": "50% 32%",
    "place": "One Canada Square, Canary Wharf",
    "alt": "One Canada Square tower at Canary Wharf",
    "credit": {
      "by": "Mark Gilbert",
      "licence": "CC BY-SA 3.0",
      "url": "https://creativecommons.org/licenses/by-sa/3.0/",
      "source": "https://commons.wikimedia.org/wiki/File:1_Canada_Square_From_Cabot_Square.jpg"
    }
  }
];
